version: '3'

services:
  api:
    image: apilne
    volumes:
      -  ~/public_html/justine-web/fakeapi:/var/www
    ports:
      - "3000:3000"
  web:
    image: nolpine
    volumes:
      -  ~/public_html/justine-web:/var/www
    ports:
      - "4000:8080"
    depends_on:
      - api
